import type { Metadata, Viewport } from 'next'
import { Lato } from 'next/font/google'
import React from 'react'
import i18n, { Locale } from '@/i18n'
import '../globals.css'

const lato = Lato({
  variable: '--font-lato',
  weight: ['400', '700', '900'],
  subsets: ['latin'],
})

type Props = {
  children: React.ReactNode
  params: Promise<{ locale: Locale }>
}

export const viewport: Viewport = {
  initialScale: 1,
  maximumScale: 1,
  width: 'device-width',
}

export async function generateStaticParams() {
  return i18n.config.locales.map((locale) => ({ locale: locale }))
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params }: Readonly<Props>) {
  const { locale } = await params

  return (
    <html lang={locale}>
      <body className={`${lato.variable} antialiased`}>{children}</body>
    </html>
  )
}
